// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeht3EsD7weDWB74fBaM2rkzGEGS7b5hA',
    appId: '1:450009094966:ios:9128ec59ea0abf8e9db197',
    messagingSenderId: '450009094966',
    projectId: 'wordgame-44c58',
    storageBucket: 'wordgame-44c58.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQszqV3uL36jMeZ3J212wfi-lZUgfG6_g',
    appId: '1:450009094966:web:31e924782aba17b49db197',
    messagingSenderId: '450009094966',
    projectId: 'wordgame-44c58',
    authDomain: 'wordgame-44c58.firebaseapp.com',
    storageBucket: 'wordgame-44c58.firebasestorage.app',
    measurementId: 'G-SBBXR05FX2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQszqV3uL36jMeZ3J212wfi-lZUgfG6_g',
    appId: '1:450009094966:web:31e924782aba17b49db197',
    messagingSenderId: '450009094966',
    projectId: 'wordgame-44c58',
    authDomain: 'wordgame-44c58.firebaseapp.com',
    storageBucket: 'wordgame-44c58.firebasestorage.app',
    measurementId: 'G-SBBXR05FX2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeht3EsD7weDWB74fBaM2rkzGEGS7b5hA',
    appId: '1:450009094966:ios:9128ec59ea0abf8e9db197',
    messagingSenderId: '450009094966',
    projectId: 'wordgame-44c58',
    storageBucket: 'wordgame-44c58.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAYl5JGiM8ie1YV0vzxxh17akklS7VAQ',
    appId: '1:450009094966:android:a8203d7f4ab277fb9db197',
    messagingSenderId: '450009094966',
    projectId: 'wordgame-44c58',
    storageBucket: 'wordgame-44c58.firebasestorage.app',
  );

}